# Variables
[env]
PROJECT_DIR = { script = ["pwd"] }
CROSS_CC = "arm-linux-gnueabi-gcc"
# CUSTOM_QEMU_DIR = "/usr/share/qemu"

# Build the fuzzer
[tasks.build]
command = "cargo"
args = ["build", "--release"]

# Run the fuzzer
[tasks.run]
command = "cargo"
args = ["run"]