# Variables
[env]
PROJECT_DIR = { script = ["pwd"] }
# CROSS_CC = "arm-linux-gnueabi-gcc"
# CUSTOM_QEMU_DIR = "/usr/share/qemu"

[tasks.clean]
command = "cargo"
args = ["clean"]

# Run the fuzzer
[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["clean"]